export type DefaultSource = {
  name: string;
  url: string;
  enabled: boolean;
};

export const DEFAULT_SOURCES: DefaultSource[] = [
  { name: "koreanair-recruit", url: "https://koreanair.recruiter.co.kr/career/apply", enabled: true },
  { name: "asiana-recruit", url: "https://flyasiana.recruiter.co.kr/career/recruitment", enabled: true },
  { name: "naver-jjooo112", url: "https://blog.naver.com/jjooo112", enabled: true },
  { name: "naver-olive2269", url: "https://blog.naver.com/olive2269", enabled: true },
  { name: "naver-bongbongb0ng", url: "https://blog.naver.com/bongbongb0ng", enabled: true },
  { name: "naver-on-fly", url: "https://blog.naver.com/on_fly", enabled: true },
  { name: "instagram-crewfactory-jh", url: "https://www.instagram.com/crewfactory.hc_jh/", enabled: true },
  { name: "threads-ije-writer", url: "https://www.threads.com/@ije_writer", enabled: true },
  { name: "instagram-crewfactory-sunny", url: "https://www.instagram.com/crewfactory.hc_sunny/", enabled: true },
  { name: "instagram-koreanair", url: "https://www.instagram.com/koreanair/", enabled: true },
  { name: "instagram-wingsky", url: "https://www.instagram.com/wingsky_official/", enabled: true },
  { name: "instagram-on-fly", url: "https://www.instagram.com/on___fly/", enabled: true },
  { name: "facebook-wingskygj", url: "https://www.facebook.com/wingskygj", enabled: true },
  { name: "naver-anacast", url: "https://blog.naver.com/anacast", enabled: true },
  { name: "koreanair-recruit-main", url: "https://recruit.koreanair.com", enabled: true },
  { name: "asiana-main", url: "https://flyasiana.com/I/WS/ko/contents?menuId=KW5100", enabled: true },
  { name: "jejuair-recruit", url: "https://recruit.jejuair.net", enabled: true },
  { name: "jinair-recruit", url: "https://jinair.recruiter.co.kr", enabled: true },
  { name: "twayair-recruit", url: "https://recruit.twayair.com", enabled: true },
  { name: "airbusan-recruit", url: "https://recruit.airbusan.com", enabled: true },
  { name: "airseoul-recruit", url: "https://airseoul.recruiter.co.kr", enabled: true },
  { name: "eastarjet-recruit", url: "https://recruit.eastarjet.com", enabled: true },
  { name: "airpremia-recruit", url: "https://www.airpremia.com/kor/about/recruit", enabled: true },
  { name: "emirates-cabincrew", url: "https://www.emiratesgroupcareers.com/cabin-crew", enabled: true },
  { name: "qatar-cabincrew", url: "https://www.qatarairways.com/en/careers/customer-experience/cabin-crew-recruitment.html", enabled: true },
  { name: "etihad-cabincrew", url: "https://careers.etihad.com/content/Cabin-Crew-at-Etihad", enabled: true },
  { name: "singaporeair-cabincrew", url: "https://careers.singaporeair.com/sia/go/Cabin-Crew/689244", enabled: true },
  { name: "cathay-careers", url: "https://careers.cathaypacific.com/en", enabled: true },
  { name: "vietnamairlines-careers", url: "https://www.vietnamairlines.com/us/en/vietnam-airlines/career-with-us", enabled: true },
  { name: "scoot-careers", url: "https://careers.flyscoot.com", enabled: true },
  { name: "airmacau-hr", url: "https://www.airmacau.com.mo/eng/about/hr.html", enabled: true },
  { name: "philippineairlines-careers", url: "https://careers.philippineairlines.com", enabled: true },
  { name: "salaair-careers", url: "https://careers.salaair.com", enabled: true },
  { name: "klm-cabin", url: "https://careers.klm.com/en/working-in-the-cabin", enabled: true },
  { name: "lufthansa-cabin", url: "https://lufthansagroup.careers/en/flight-attendant", enabled: true },
  { name: "finnair-cabin", url: "https://company.finnair.com/en/careers/cabin-crew", enabled: true },
  { name: "airfrance-recruitment", url: "https://recrutement.airfrance.com/homepage.aspx?LCID=2057", enabled: true },
  { name: "ana-employ", url: "https://www.ana.co.jp/en/eur/the-ana-experience/about-ana/employ", enabled: true },
  { name: "jal-career", url: "https://www.jal.co.jp/ar/en/career", enabled: true },
  { name: "turkishairlines-cabincrew", url: "https://careers.turkishairlines.com/en-us/cabin-crew", enabled: true },
  { name: "crewkorea", url: "https://crewkorea.com", enabled: true },
  { name: "wingsky-now-recruit", url: "http://wingsky.co.kr/NOW_recruit", enabled: true },
];
